# options for analysis running
run:
  concurrency: 4
  timeout: 5m
  modules-download-mode: readonly

linters-settings:
  govet:
    check-shadowing: true
    settings:
      printf: # analyzer name, run `go tool vet help` to see all analyzers
        funcs: # run `go tool vet help printf` to see available settings for `printf` analyzer
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Infof
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Warnf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Errorf
          - (github.com/golangci/golangci-lint/pkg/logutils.Log).Fatalf

    enable-all: true
    disable:
      - fieldalignment
  goimports:
    local-prefixes: github.com/signalfx/splunk-otel-collector-operator
  gofmt:
    simplify: true
  maligned:
    suggest-new: true
  misspell:
    locale: US

linters:
  disable:
    - errcheck
    - goheader
  enable:
    - exhaustive
    - exportloopref
    - godot
    - gofmt
    - goimports
    - gosec
    - govet
    - misspell
    - revive
    - staticcheck
    - unconvert
    - unparam

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    # Exclude some linters from running on tests files.
    - text: "G404:"
      linters:
        - gosec
    - text: "G402:"
      linters:
        - gosec

