apiVersion: kuttl.dev/v1beta1
kind: TestSuite
crdDir: ./tests/_build/crds/
artifactsDir: ./tests/_build/artifacts/
kindNodeCache: true
kindContainers:
  - local/splunk-otel-operator:e2e
commands:
  - command: make cert-manager
  - command: kubectl apply -f ./tests/_build/manifests/01-splunk-otel-operator.yaml
  - command: kubectl wait --timeout=5m --for=condition=available deployment splunk-otel-operator-controller-manager -n splunk-otel-operator-system
  - command: sleep 5
testDirs:
  - ./tests/e2e/
timeout: 150