apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: splunk-otel-collector-operator-metrics-reader
rules:
- nonResourceURLs:
  - /metrics
  verbs:
  - get
