
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: mutating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /mutate-o11y-splunk-com-v1alpha1-splunkotelagent
  failurePolicy: Fail
  name: msplunkotelagent.kb.io
  rules:
  - apiGroups:
    - o11y.splunk.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - splunkotelagents
  sideEffects: None

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  creationTimestamp: null
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  - v1beta1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-o11y-splunk-com-v1alpha1-splunkotelagent
  failurePolicy: Fail
  name: vsplunkotelagent.kb.io
  rules:
  - apiGroups:
    - o11y.splunk.com
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - splunkotelagents
  sideEffects: None
