# permissions for end users to edit agents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-editor-role
rules:
- apiGroups:
  - otel.splunk.com
  resources:
  - agents
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - otel.splunk.com
  resources:
  - agents/status
  verbs:
  - get
