resources:
- service_account.yaml
- role.yaml
- role_binding.yaml
- leader_election_role.yaml
- leader_election_role_binding.yaml

# Comment the following 4 lines if you want to disable
# the auth proxy (https://github.com/brancz/kube-rbac-proxy)
# which protects your /metrics endpoint.
#- auth_proxy_service.yaml
#- auth_proxy_role.yaml
#- auth_proxy_role_binding.yaml
#- auth_proxy_client_clusterrole.yaml

# the following roles and role bindings are used
# by the deployed collector instances
# TODO(splunk): use different roles/service accounts for
# agent, clusterreceiver and gateway
- splunk_role.yaml
- splunk_role_binding.yaml
