name: "End-to-end tests"

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  e2e-tests:
    name: End-to-end tests
    runs-on: ubuntu-20.04
    strategy:
      fail-fast: false
      matrix:
       kube-version:
       - "1.23"
       - "1.24"
       - "1.25"

    steps:

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19

    - name: Check out code into the Go module directory
      uses: actions/checkout@v4

    - name: "install tools"
      run: make install-tools

    - name: "install kuttl"
      run: ./hack/install-kuttl.sh

    - name: "run tests"
      env:
        KUBE_VERSION: ${{ matrix.kube-version }}
      run: make prepare-e2e e2e KUBE_VERSION=$KUBE_VERSION
